# This file is managed by Nix

theme = "onedark"


[editor]
soft-wrap = { enable = true }
true-color = true
color-modes = true

[editor.whitespace.render]
tab = "all"

[editor.whitespace.characters]
tab = "â†’"

