[package]
name = "gloc"
version = "0.1.0"
edition = "2024"

[dependencies]
tempfile = "3.8"        # For creating temp dirs
clap = { version = "4.5", features = ["derive"] }  # For CLI args
colored = "3.0"         # For colorful output