[package]
name = "gitinit" # Git init
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }  # For CLI args
colored = "3.0"         # For colorful output
chrono = "0.4"