BasedOnStyle: LLVM
IndentWidth: 4
TabWidth: 4
UseTab: Never
ColumnLimit: 100
AlwaysBreakTemplateDeclarations: true
BreakBeforeBraces: Attach
AllowShortFunctionsOnASingleLine: Inline
SpaceBeforeParens: ControlStatements
